name: Publish NuGet

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: |
          # take first 8 chars of the SHA to keep the version string short
          SHA8=${GITHUB_SHA:0:8}
          dotnet pack \
            --configuration Release \
            --no-build \
            --output ./nupkgs \
            /p:PackageVersion=1.0.${GITHUB_RUN_NUMBER}-$SHA8

      - name: Push
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push ./nupkgs/*.nupkg \
            --api-key $NUGET_API_KEY \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
